### ISSUE TITLE
Add support for aapt2

### ISSUE THREAD

**Issue by RohitVerma882** [hosni-fraj/Aide-Pro#5]
New version of library doesn't working, need to upgrade aapt

**Comment by eirv** [comment]
This is open source in China

**Comment by RohitVermaOP** [comment]
> This is open source in China

Link?

**Comment by eirv** [comment]
![Screenshot_2022-03-29-16-08-01-865_bin mt plus](https://user-images.githubusercontent.com/64970244/160564397-2a2c82ff-d100-4237-936d-c9e8adfafae4.jpg)

**Comment by eirv** [comment]
![Screenshot_2022-03-29-16-09-27-343_com tencent mobileqq](https://user-images.githubusercontent.com/64970244/160564627-9afd6ae3-9407-4ebf-b55f-441d35faeb1b.jpg)
You can get the source code here

**Comment by RohitVermaOP** [comment]
> ![Screenshot_2022-03-29-16-09-27-343_com tencent mobileqq](https://user-images.githubusercontent.com/64970244/160564627-9afd6ae3-9407-4ebf-b55f-441d35faeb1b.jpg) You can get the source code here

??

**Comment by eirv** [comment]
![Screenshot_2022-03-29-16-18-27-625_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/64970244/160566606-b59194df-cbd4-45e3-9d30-07c864741cae.jpg)
So that's the source code

**Comment by RohitVermaOP** [comment]
Where is link?

**Comment by eirv** [comment]
No Link
QQ Group number537756994

**Comment by eirv** [comment]
Please try your best to register your account and download it

**Comment by eirv** [comment]
https://share.weiyun.com/NG0bI0X5

**Comment by eirv** [comment]
He didn't put the source code on Github, so there's no link
